version: '3'
services:
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/notifications?authSource=admin
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - mongodb
      - rabbitmq

  worker:
    build: .
    command: npm run worker
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/notifications?authSource=admin
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongo_data: